### ISSUE TITLE
Error in bulkAddActivities.loop

### ISSUE THREAD

**Issue by gdoumen** [incyclist/services#146]
Detected in Logs:

```
2024-11-10T08:43:21.323Z,version:0.8.32,message:preload route list
2024-11-10T08:43:21.325Z,version:0.8.32,message:preload workout list
2024-11-10T08:43:21.325Z,version:0.8.32,message:preload activity list
2024-11-10T08:43:21.326Z,version:0.8.32,message:init done
2024-11-10T08:43:21.329Z,version:0.8.32,message:App.render()
2024-11-10T08:43:21.355Z,version:0.8.32,message:ANT+ connecting ...
2024-11-10T08:43:21.422Z,version:0.8.32,message:Ble connect request
2024-11-10T08:43:21.429Z,version:0.8.32,message:Loading Google Maps API
2024-11-10T08:43:21.438Z,version:0.8.32,message:page shown,page:Pairing
2024-11-10T08:43:21.439Z,version:0.8.32,message:capability info,capability:control,devices:Tacx Neo 2T 61115;Ant+FE 61115,selected:Tacx Neo 2T 61115,disabled:false
2024-11-10T08:43:21.439Z,version:0.8.32,message:capability info,capability:power,devices:Tacx Neo 2T 61115;Ant+FE 61115;Ant+PWR 61115,selected:Tacx Neo 2T 61115,disabled:false
2024-11-10T08:43:21.439Z,version:0.8.32,message:capability info,capability:cadence,devices:Tacx Neo 2T 61115;Ant+FE 61115;Ant+SC 61115;Ant+PWR 61115;Ant+CAD 15374,selected:Tacx Neo 2T 61115,disabled:false
2024-11-10T08:43:21.439Z,version:0.8.32,message:capability info,capability:speed,devices:Tacx Neo 2T 61115;Ant+FE 61115;Ant+SC 61115;Ant+PWR 61115,selected:Tacx Neo 2T 61115,disabled:false
2024-11-10T08:43:21.439Z,version:0.8.32,message:capability info,capability:heartrate,devices:HRM-Dual:298650;Ant+HR 36506,selected:Ant+HR 36506,disabled:false
2024-11-10T08:43:21.440Z,version:0.8.32,message:adapter list out of sync,missing:c073e6be-a728-465e-ac71-d1ddd9654c2e
2024-11-10T08:43:21.506Z,version:0.8.32,message:Pairing: waiting for interfaces,interfaces:ant
2024-11-10T08:43:21.523Z,version:0.8.32,message:Ble connect result: success
2024-11-10T08:43:21.524Z,version:0.8.32,message:interface state changed,interface:ble,state:connected
2024-11-10T08:43:21.530Z,version:0.8.32,message:Pairing: waiting for interfaces,interfaces:ant
2024-11-10T08:43:21.536Z,version:0.8.32,message:preload workout list completed,cards:{myRoutes:1}
2024-11-10T08:43:21.705Z,version:0.8.32,message:Google Maps API loaded,duration:276
2024-11-10T08:43:22.735Z,version:0.8.32,message:preload route list completed
2024-11-10T08:43:22.745Z,version:0.8.32,message:RoutesList loaded,counts:{myRoutes:23,selected:10,alternatives:13},titles:{
myRoutes:Import Route,Free Ride,Alcudia - Orient,Cap Formentor,Cycling Challenge,First stage Vuelta Mallorca,Furka-Grimsel-Susten 2015,German Wine Route,Gonso Classic,Hornisgrinde 2015,Julier pass,Kandel 2015,Lofoten,Manacor - Porto Christo - Can Picafort,Menorca West,Mühlviertel,Passo Pordoi,Sagres,
Schauinsland 2015,Val d'Anniviers,Valdrôme 2 - Col du Fays, Col de Rossas ,Manghen,S.Pellegrino-Valles con Pedrotti,
selected:Arnbach,Menglonnais,Polygyros,Sydney Opera House and Botanic Garden,Seaside Vancouver,Malaga City Tour,Würzjoch ,Captain  Cook Highway,Ventoux - Malaucene,Sarti-Toroni-Sarti,
alternaties:Valdrôme 1 - Col de Prémol,Valdrôme 3 - Les Claps de Luc,Alferce,Allgäu,Col du Galibier,Corvara,Mallorca: Alcudia - Sant Elm,Menorca West,Monte Baldo,Queichtal bikeway,Rhine Bikeway,Rhine Cycle Path 2022,Trollstigen}
2024-11-10T08:43:22.866Z,version:0.8.32,message:error,error:{},fn:bulkAddActivities.loop

```

update (17.11.24)
```
2024-11-17T10:53:30.010Z,version:0.8.36,message:error,fn:bulkAddActivities.loop,error:Cannot destructure property 'id' of 'e' as it is null.,
stack:TypeError: Cannot destructure property 'id' of 'e' as it is null.\n
at t.buildSummary (file:///C:/Users/Krasselt/AppData/Roaming/Incyclist/react/static/js/2.b30e41cc.chunk.js:1:5366246)\n
at file:///C:/Users/Krasselt/AppData/Roaming/Incyclist/react/static/js/2.b30e41cc.chunk.js:1:6463122\n
at Array.forEach (<anonymous>)\n
at d.<anonymous> (file:///C:/Users/Krasselt/AppData/Roaming/Incyclist/react/static/js/2.b30e41cc.chunk.js:1:6462950)\n    
at Generator.next (<anonymous>)\n
at a (file:///C:/Users/Krasselt/AppData/Roaming/Incyclist/react/static/js/2.b30e41cc.chunk.js:1:6455790)
```

**Comment by gdoumen** [comment]
fixed in UI version 0.8.37
