### ISSUE TITLE
error in getDashboardDisplayProperties

### ISSUE THREAD

**Issue by gdoumen** [incyclist/services#180]
(observed in logs) - seems to happen once immediately after start of activity

```
2024-12-08T15:33:12.168Z,version:0.8.50,page:Search,dialog:RouteDetails,message:Dialog closed,title:Valdrôme 2 - Col du Fays, Col de Rossas
2024-12-08T15:33:12.172Z,version:0.8.50,message:previous rides,route:Valdrôme 2 - Col du Fays, Col de Rossas ,cnt:152,settings:{startPos:0,realityFactor:100}
2024-12-08T15:33:12.173Z,version:0.8.50,message:Attempting to start a ride,id:3aefb91a-be3e-42c1-b7cb-47bc80bebce5,title:Valdrôme 2 - Col du Fays, Col de Rossas ,videoUrl:video:///C:\\Rad\\FR_Valdrome_Part_2.mp4,readyToStart:true
2024-12-08T15:33:12.365Z,version:0.8.50,page:Search,message:page closed
2024-12-08T15:33:12.373Z,version:0.8.50,message:reset state
2024-12-08T15:33:12.374Z,version:0.8.50,message:adding processor,processor:RouteOptionSelector
2024-12-08T15:33:12.375Z,version:0.8.50,message:updateDimensions,width:1564,height:980
2024-12-08T15:33:12.376Z,version:0.8.50,message:reset state
2024-12-08T15:33:12.376Z,version:0.8.50,message:Client Mounted,appDir:**filtered**
2024-12-08T15:33:12.377Z,version:0.8.50,message:user loaded,source:settings,user:**filtered**
2024-12-08T15:33:12.422Z,version:0.8.50,message:Error,fn:getDashboardDisplayProperties,error:Cannot read properties of undefined (reading 'speed'),stack:TypeError: Cannot read properties of undefined (reading 'speed')\n    
        at i.getCurrentValues (file:///C:/Users/extern/AppData/Roaming/Incyclist/react/static/js/2.028b7779.chunk.js:1:6586637)\n
        at i.getDashboardDisplayProperties (file:///C:/Users/extern/AppData/Roaming/Incyclist/react/static/js/2.028b7779.chunk.js:1:6584525)\n    
        at A.createActivityUpdateMessage (file:///C:/Users/extern/AppData/Roaming/Incyclist/react/static/js/main.f8232c97.chunk.js:1596:21856)\n    
        at A.setPosition (file:///C:/Users/extern/AppData/Roaming/Incyclist/react/static/js/main.f8232c97.chunk.js:1596:44935)\n
        at A.setRoutePosition (file:///C:/Users/extern/AppData/Roaming/Incyclist/react/static/js/main.f8232c97.chunk.js:1596:35695)\n    
        at A.setRouteStartPosition (file:///C:/Users/extern/AppData/Roaming/Incyclist/react/static/js/main.f8232c97.chunk.js:1596:35430)\n    
        at A.showRidePageFromNewUI (file:///C:/Users/extern/AppData/Roaming/Incyclist/react/static/js/main.f8232c97.chunk.js:1596:27605)
2024-12-08T15:33:12.448Z,version:0.8.50,message:ride screen initialized in new UI,route:....
```

**Comment by gdoumen** [comment]
fixed in UI Versoin 0.8.56
